---
- name: Install Neo Vim
  hosts: 127.0.0.1
  become: yes
  tasks:
    - name: Ensure apt is up to date
      apt:
        update_cache: yes
      
    - name: Download Neovim app image
      get_url:
        url: https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
        dest: /tmp/nvim.appimage

    - name: Modify access rights
      file:
        path: /tmp/nvim.appimage
        mode: u+x

    - name: Move app image to user bin folder
      copy:
        src: /tmp/nvim.appimage
        dest: /usr/local/bin/nvim
        remote_src: yes

    - name: Update bashrc
      copy:
        src: bashrc
        dest: ~/.bashrc

    - name: Remove existing Neovim configuration
      file:
        path: ~/.local/share/nvim
        state: absent

    - name: Clone Neovim configuration repository
      git:
        repo: https://github.com/S010MON/nvim.git
        dest: ~/.config/nvim
        depth: 1
        
- name: Install Tmux
  hosts: 127.0.0.1
  become: yes
  tasks:
  
    - name: Install TMUX dependencies
      apt:
        name:
          - libevent-dev
          - ncurses-dev
        state: present

    - name: Download TMUX source
      get_url:
        url: https://github.com/tmux/tmux/releases/download/3.3a/tmux-3.3a.tar.gz
        dest: /tmp/tmux-3.3a.tar.gz

    - name: Extract TMUX source
      unarchive:
        src: /tmp/tmux-3.3a.tar.gz
        dest: /tmp
        remote_src: yes

    - name: Configure TMUX
      command: ./configure
      args:
        chdir: /tmp/tmux-3.3a

    - name: Make and install TMUX
      make:
        chdir: /tmp/tmux-3.3a
        target: install
        
    - name: Clone TMUX package manager
      become: yes
      become_user: "{{ ansible_env.USER }}"
      git:
        repo: https://github.com/tmux-plugins/tpm
        dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"

    - name: Copy TMUX configuration file
      become: yes
      become_user: "{{ ansible_env.USER }}"
      copy:
        src: tmux.conf
        dest: "{{ ansible_env.HOME }}/.config/tmux/tmux.conf"

    - name: Restart the shell
      shell: exec $SHELL
      args:
        executable: /bin/bash

