---
- name: Software Installation
  hosts: 127.0.0.1
  become: yes
  tasks:

  - name: Ensure apt is up to date
    apt:
      update_cache: yes
      
  - name: Install Tools
    apt:
      name: 
        - git
        - inetutils-ping
        - telnet
        - net-tools
        - vim
        - iotop
        - tcpdump
        - build-essential
        - cmake
      
- name: Install Docker
  hosts: 127.0.0.1
  become: yes
  tasks:

  - name: Ensure apt is up to date
    apt:
      update_cache: yes

  - name: Install required packages
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
      
  - name: Add Dockers official GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      file: /etc/apt/keyrings/docker.asc
      state: present

  - name: Add Docker repository
    apt_repository:
      repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Install Docker
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      state: latest
      update_cache: true

  - name: Add all users to docker group
    shell: |
      groupadd docker
      for user in $(cut -d: -f1 /etc/passwd);
      do
        if id -u "$user" >/dev/null 2>&1; then
            usermod -aG docker $user;
        fi
      done
